server:
  port: 8001

spring:
  application:
    name: taxdeclaration-service
  datasource:
    username: ''
    password: ''
    url: jdbc:postgresql://localhost:5432/taxdeclarationservice
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  security:
    user:
      name: 'user'
      password: 'user'
taxdeclaration:
  app:
    jwtSecret: 'taxdeclarationservice'
    jwtExpirationMs: '86400000'
    jwtRefreshExpirationMs: '86400000'
    baseUrlLocal: 'http://localhost:8080/'